//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking_Slot
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public string user_name { get; set; }
        public int role_id { get; set; }
    }
}
